### ISSUE TITLE
Confusing Readme

### ISSUE THREAD

**Issue by JoFont** [alyssaxuu/flowy#13]
Hello, I'm slightly confused as to what functionality does this codebase actually provide. Following the readme, the result (at least the one I arrived to) has nothing to do with what you see in the demo. So my question is:

Does this just provide bare-bones functionality for a system that needs custom implementation or, is this supposed to ship with some sort of UI resembling the demo?
In case of the latter, then I'm clearly doing something wrong. Otherwise, I feel like the Readme could provide a bit of clarification on how to implement this functionality.

I believe the case is the latter as the demo folder is way more complex than the engine one.

I case of doubt, my result after just following the read-me is just a div with text and a type error when trying to drag it.

Thank you very much,
Have  a good one.

**Comment by alyssaxuu** [comment]
Hey, the demo is simply a preview of what the engine can do. As explained in the ReadMe, you can design the blocks however you want, and it works the same way, connecting with the arrows and with all the same functionality. I didn't ship it together with a UI as I wanted the engine to be extremely minimal and to allow it to be extremely versatile.

As per the demo folder being "way more complex" it's mostly because I created a "fake UI" to showcase the kind of product that could be built with the engine, the flowchart part though is incredibly simple and lightweight.

If you think it would be good to have a version that comes with a simple UI that can be customized I could also do that, maybe as a starter project that people can edit.

**Comment by JoFont** [comment]
Hey @alyssaxuu, Ok, so I managed to get it working, I had to add styles because I was getting confused of where things were and type error was because js was loading before content.
I still find it confusing to understand the boundaries of the canvas and where the dropping zone starts and ends.

Yes! I think a version with default UI would be great! Though I now understand how this is supposed to work. I wouldn't default to a starter kit, but maybe a set of components that could be inserted at will (say, a dropping zone with default styles, a block component a sidebar/block list component, etc) but, that's just my opinion.

Anyway, thank you very much for promptly clarifying my concerns! :)

**Comment by fqure** [comment]
> If you think it would be good to have a version that comes with a simple UI that can be customized I could also do that, maybe as a starter project that people can edit.

Perhaps adding a js edit-in-place might make for a better demo so that people could adjust to their frame of context.
