### ISSUE TITLE
How to rebuild the tree without the HTML part ?

### ISSUE THREAD

**Issue by Titof974** [alyssaxuu/flowy#40]
Do you think it's possible to rebuild the tree without the HTML ? How to do it ?

**Comment by alyssaxuu** [comment]
Not sure what you mean - there's the `flowy.import()` method to load a tree from JSON data.

**Comment by Jisco** [comment]
Hi,
i think @Titof974 means the "html" property in the exported JSON Object.

I see in the code it's used to set the "innerHTML" of the canvas div. So it's currently not possible to rebuild the flowchart only with the rest (without the "html" property) of the JSON Object. 

Right?

**Comment by alyssaxuu** [comment]
Ah right, yeah, this is because there is not a default "template" for the blocks, so the only way to ensure that the flowchart you created (with the styling/fields/other you've customized) will show as it previously was. Obviously if I "enforced" using the design from the demo the HTML property in the export wouldn't be needed and just from the JSON you could create the tree. But yeah, the idea is to make the library as versatile as possible, so people can make blocks for a large variety of use-cases and even drastically different to what I proposed in the demo.

**Comment by yellow1912** [comment]
@alyssaxuu It is not so efficient to save the complete HTML inside the database for example, normally you only want to save the tree structure. It would be nice to allow having a render method. This way we can re-render the the blocks by just passing the blocks data. It also allows you to easily update the view any time you need as well as customizing the view of each block on the fly.

**Comment by wscjxky** [comment]
may be you can try it .
https://github.com/alyssaxuu/flowy/issues/148
