### ISSUE TITLE
Prevent accidental removal

### ISSUE THREAD

**Issue by yellow1912** [alyssaxuu/flowy#48]
Currently (as can be seen on this demo: https://alyssax.com/x/flowy/), if we add:
1. 1 parent block
2. 1 child block

Then if we move the child block a bit outside of the perimeter then the child block will be deleted. This can be a disaster if you have a huge tree and you accidentally deleted 1 big branch in that tree (happened to me). I think there should be an option to prevent that to happen, and somehow allow manually trigger a method like flowy.deleteBlock.

**Comment by alyssaxuu** [comment]
Yeah I can see how that can be an issue. I'm just not sure what the expected behaviour should be here. Should there be a modal that asks if you want to delete the blocks, and if not they should re-attach where they were before? Should it only delete the blocks when moved towards a "deletion area" such as on the left (or maybe creating a sort of "trash bin" icon that pops up while moving blocks that you can throw blocks into), and otherwise either re-attach where it was if dropped anywhere in the canvas or to any other spot you want to move it to?

I'm just wondering. I suppose ideally people might want new trees to form when dropped in the canvas, I just haven't figured out an intuitive implementation for that yet (it's tricky because of how the blocks are centered and aligned, they automatically position themselves in a way that they don't overlap & don't get cut off, but if people were able to drop blocks anywhere, it might not be wise to prevent overlapping).

**Comment by yellow1912** [comment]
I think all the options you listed are good. Perhaps we could do a beforeRemove which may return a Promise which can either resolve or reject? That way:

1. It will be up to the developer to handle the logic (either a popup modal, or perhaps a long running ajax check to the server etc)
2. For the option that allows dropping to a delete zone, I also like that idea but perhaps that can be simplified by exposing an api to delete a specific block. (And an api to add a block at a specific location is also nice)

Either way, if the delete is not allowed, the node can be set back to where it was.

I like the current auto-position feature, I think it's nice to keep. I have seen other libs that force you to manually delete (perhaps via a trash icon) and allow you to re-arrange the blocks. I don't think the re-arrangement is necessary here in this case if we want to keep the lib simple.

**Comment by alyssaxuu** [comment]
> I think all the options you listed are good. Perhaps we could do a beforeRemove which may return a Promise which can either resolve or reject? That way:
> 
> 1. It will be up to the developer to handle the logic (either a popup modal, or perhaps a long running ajax check to the server etc)
> 2. For the option that allows dropping to a delete zone, I also like that idea but perhaps that can be simplified by exposing an api to delete a specific block. (And an api to add a block at a specific location is also nice)
> 
> Either way, if the delete is not allowed, the node can be set back to where it was.
> 
> I like the current auto-position feature, I think it's nice to keep. I have seen other libs that force you to manually delete (perhaps via a trash icon) and allow you to re-arrange the blocks. I don't think the re-arrangement is necessary here in this case if we want to keep the lib simple.

Just added the new method. Kept it simple, you pass a function that will re-attach the blocks with the previous parent if it returns true.
