### ISSUE TITLE
Changing block height

### ISSUE THREAD

**Issue by dmlnc** [alyssaxuu/flowy#67]
Hey @alyssaxuu 
Excellent work, thank you

Maybe you know how can I change height of block or position of another blocks after replace blockyinfo text from input field?

<img width="515" alt="Снимок экрана 2020-05-14 в 08 01 24" src="https://user-images.githubusercontent.com/36060841/81894754-3e019180-95b9-11ea-8e08-858caca399cd.png">

Thanks again

**Comment by alyssaxuu** [comment]
Do you mean altering the block dimensions after it has been placed? Currently that won't readjust the flowchart unfortunately  - I see a few options here, either detecting block dimension changes on the library end and using that to tweak the positioning of the blocks, or something kind of like #53 where the developer can call a render method whenever a change has been made to rearrange everything.

Personally I might be keen on the former just because it feels more user-friendly. I'll explore implementing that (although not entirely sure if that is your question ^^).
